apiVersion: v1
kind: Pod
metadata:
  name: my-web
  labels:
    app: nginx
    env: prod
    owner: IgorZnamensky
    tier: front-end
    hui: big_hui
spec:
  containers:
    - name: apache-container
      image: nginx:latest
      ports:
        - containerPort: 80